#!/usr/bin/env python3
"""
run_maze.py -- Feed any maze .json to the C solver.

Usage:
    python scripts/run_maze.py ../simulator/mazes/sample_maze4.json
    python scripts/run_maze.py ../simulator/mazes/sample_maze.json

What it does:
    1. Reads the maze .json file
    2. Generates test/_maze_data.h (C arrays from the JSON)
    3. Compiles run_maze.c + all solver sources against it
    4. Runs the .exe and prints the result
    5. Cleans up the generated header
"""
import json, subprocess, sys, os
from pathlib import Path

# -- paths --
ROBOT_CODES = Path(__file__).resolve().parent.parent   # robot codes/
INC_DIR     = ROBOT_CODES / "inc"
SRC_DIR     = ROBOT_CODES / "src"
TEST_DIR    = ROBOT_CODES / "test"
BUILD_DIR   = ROBOT_CODES / "build"
DATA_H      = TEST_DIR / "_maze_data.h"                # generated
EXE         = BUILD_DIR / "run_maze.exe"
GCC         = "gcc"


def die(msg):
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def warn(msg):
    print(f"WARNING: {msg}", file=sys.stderr)


# -- generate _maze_data.h --

def generate_header(json_path: Path):
    """Read the .json maze, write _maze_data.h."""
    if not json_path.exists():
        die(f"file not found: {json_path}")

    with open(json_path, "r", encoding="utf-8") as fh:
        data = json.load(fh)

    nodes       = data["nodes"]
    edges       = data["edges"]
    start       = int(data["start"])
    target      = int(data["target"])
    n_nodes     = len(nodes)
    n_edges     = len(edges)

    # Validate contiguous node IDs 0..N-1
    for i in range(n_nodes):
        if str(i) not in nodes:
            die(f"node '{i}' missing -- nodes must be contiguous 0..{n_nodes-1}")

    # Build coordinate array
    coord_lines = []
    for i in range(n_nodes):
        x, y = nodes[str(i)]
        coord_lines.append(f"    {{{x},{y}}}")

    # Build edge array
    edge_lines = []
    for a, b in edges:
        edge_lines.append(f"    {{{a},{b}}}")

    header = f"""/* Auto-generated by scripts/run_maze.py -- DO NOT EDIT.
 * Source: {json_path}
 */
#ifndef MAZE_DATA_H
#define MAZE_DATA_H
#include "maze_types.h"

static const char* maze_data_name = "{json_path.name}";

#define MAZE_DATA_N_NODES   {n_nodes}
#define MAZE_DATA_START_IDX {start}
#define MAZE_DATA_TARGET_IDX {target}

static const MazeCoord maze_data_coords[{n_nodes}] = {{
{",\n".join(coord_lines)}
}};

static const uint16_t maze_data_edges[{n_edges}][2] = {{
{",\n".join(edge_lines)}
}};

#define MAZE_DATA_N_EDGES (sizeof(maze_data_edges) / sizeof(maze_data_edges[0]))

#endif /* MAZE_DATA_H */
"""

    DATA_H.parent.mkdir(parents=True, exist_ok=True)
    DATA_H.write_text(header, encoding="utf-8")
    return n_nodes, n_edges


# -- compile --

SOURCES = [
    SRC_DIR / "maze_graph.c",
    SRC_DIR / "maze_robot.c",
    SRC_DIR / "maze_explore.c",
    SRC_DIR / "maze_proof.c",
    SRC_DIR / "maze_fastrun.c",
    SRC_DIR / "maze_solver.c",
    TEST_DIR / "run_maze.c",
]

CFLAGS = [
    "-std=c11", "-Wall", "-Wextra", "-pedantic",
    f"-I{INC_DIR}",      # inc/
    f"-I{TEST_DIR}",      # test/ (for _maze_data.h)
    "-lm",
]


def compile_sources():
    """Run gcc. Returns exit code."""
    BUILD_DIR.mkdir(parents=True, exist_ok=True)

    cmd = [GCC] + CFLAGS + [str(s) for s in SOURCES] + ["-o", str(EXE)]
    print(f"  [compile] {' '.join(cmd)}")
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        return result.returncode

    if result.stderr.strip():
        print(result.stderr, file=sys.stderr)
    return 0


# -- run --

def run_exe():
    """Run the compiled .exe. Returns exit code."""
    print(f"  [run] {EXE}")
    print()
    result = subprocess.run([str(EXE)])
    return result.returncode


# -- cleanup --

def cleanup():
    if DATA_H.exists():
        DATA_H.unlink()
        print(f"\n  [clean] removed {DATA_H.name}")


# -- main --

def main():
    if len(sys.argv) < 2:
        print(f"Usage:  python {Path(__file__).name} <maze.json>")
        print(f"Example: python scripts/run_maze.py ../simulator/mazes/sample_maze4.json")
        sys.exit(1)

    json_path = Path(sys.argv[1]).resolve()
    print(f"=== Maze Runner ===")
    print(f"  Maze:  {json_path}")

    # Step 1: generate header
    n_nodes, n_edges = generate_header(json_path)
    print(f"  Header: {DATA_H}  ({n_nodes} nodes, {n_edges} edges)")

    # Step 2: compile
    rc = compile_sources()
    if rc != 0:
        cleanup()
        die(f"compilation failed (exit code {rc})")

    # Step 3: run
    rc = run_exe()

    # Step 4: clean up
    cleanup()

    sys.exit(rc)


if __name__ == "__main__":
    main()
